import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Home ",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.className} flex flex-col items-center`}>
                <Header />
                <main className="py-20 px-8 w-full max-w-screen-2xl">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
